version: '3.8'

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    command: npm run start
    container_name: app-qtim
    # ports:
    #   - "3000:3000"
    environment:
      - NODE_ENV=${NODE_ENV:-development}
    volumes:
      - .:/home/node
      - node_modules:/home/node/node_modules
    depends_on:
      - db
      - redis

  db:
    image: postgres:17-alpine
    volumes:
      - ./db-init.sh:/docker-entrypoint-initdb.d/init.sh
      - pg-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
  
  redis:
    image: redis:8.0
    container_name: redis-qtim
    ports:
      - "6379:6379"
  
  redisinsight:
    image: redis/redisinsight:latest
    container_name: redisinsight-qtim
    ports:
      - "5540:5540"
    depends_on:
      - redis

volumes:
  node_modules:
  pg-data:
