version: '3'

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - .env.development.local
    command: "npm run start:development"
    container_name: app-qtim
    ports:
      - "${APP_PORT}:${APP_PORT}"
    volumes:
      - .:/home/node
      - node_modules:/home/node/node_modules
    depends_on:
      - db
      - redis

  db:
    image: postgres:17-alpine
    env_file:
      - .env.development.local
    volumes:
      - pg-data:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_HOST=${DB_HOST}
  
  redis:
    image: redis:8.0
    container_name: redis-qtim
    env_file:
      - .env.development.local
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    ports:
      - "${REDIS_PORT}:6379"
  
  redisinsight:
    image: redis/redisinsight:latest
    container_name: redisinsight-qtim
    volumes:
      - redis-data:/var/lib/redis/data
    ports:
      - "5540:5540"
    depends_on:
      - redis

volumes:
  node_modules:
  redis-data:
  pg-data:
